asistencias/urls.py
from django.urls import path, include
from . import views 


app_name = 'asistencias'

urlpatterns = [
    path('', views.home, name='home'),

    # Alumno / nivel 1
    path('perfil/', views.perfil, name='perfil'),
    path('diplomaturas/', views.listar_diplomaturas, name='listar_diplomaturas'),
    path('materias/', views.listar_materias, name='listar_materias'),
    path('inscribirse/diplomatura/', views.insc_diplomatura_por_codigo, name='insc_diplomatura_codigo'),
    path('inscribirse/materia/', views.insc_materia_por_codigo, name='insc_materia_codigo'),
    path('clases/<int:materia_id>/', views.ver_clases_materia, name='ver_clases'),
    path('clases/<int:clase_id>/presente/', views.marcar_presente, name='marcar_presente'),

    # Tokens
    path('token/usar/', views.usar_token, name='usar_token'),

    # Docente / nivel 2
    path('materias/crear/', views.crear_materia, name='crear_materia'),
    path('materias/<int:materia_id>/crear-clase/', views.crear_clase, name='crear_clase'),
    path('materias/<int:materia_id>/presentes/', views.listado_presentes, name='listado_presentes'),
    path('materias/<int:materia_id>/generar-token-adjunto/', views.generar_token_adjunto, name='token_adjunto'),

    # Coordinador / nivel 3
    path('diplomaturas/crear/', views.crear_diplomatura, name='crear_diplomatura'),
    path('diplomaturas/<int:diplo_id>/cargar-excel/', views.cargar_excel_inscripciones, name='cargar_excel'),

    # Reportes
    path('reportes/exportar/', views.exportar_reportes, name='exportar_reportes'),

    # Público
    path('publico/', views.publico, name='publico'),
    path('publico/consulta/', views.consulta_publica, name='consulta_publica'),

    #desincribirse de una materia
    path('materias/<int:materia_id>/desinscribirse/', views.desinscribirse_materia, name='desinscribirse_materia'),

    #exportar datos
    path('exportar/xlsx/', views.exportar_xlsx, name='exportar_xlsx'),

]

diplomaturas/urls.py
from django.contrib import admin #importo de django el modulo admin
from django.urls import path, include #path me sirve para definir las rutas, include me sirve para incluir las urls de otras apps
from django.contrib.auth import views as auth_views #importo las vistas de autenticacion y las renombro como auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'), #template_name define la plantilla que se usara para el login, y name es el nombre de la ruta, que se puede invocar en otros lugares usando simplemente el nombre 'login'
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), #en este caso no usa template_name porque por defecto ya esta seteado en registration/logged_out.html
    path('', include('asistencias.urls', namespace='asistencias')), # el '' indica la ruta raiz, y include me permite incluir las urls definidas en la app asistencias
    path('accounts/', include('allauth.urls')),    # registro/login/confirmación email
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>{% block title %}Asistencias Diplomaturas{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'core/styles.css' %}?v={% now 'U' %}">
</head>
<body>
  <header class="topbar">
    <div class="container">
      <a class="brand" href="{% url 'asistencias:home' %}">Asistencias</a>

      <nav class="navbar">
        <div class="nav-left">
          <a href="{% url 'asistencias:home' %}">Inicio</a>

          {% if request.user.is_authenticated %}
            <a href="{% url 'asistencias:publico' %}">Dar Presente</a>
            <a href="{% url 'asistencias:consulta_publica' %}">Consultar</a>
            <a href="{% url 'asistencias:insc_materia_codigo' %}">Inscribirse a materia</a>

            {% if request.user.nivel == 3 or request.user.nivel == 5 %}
              <a href="{% url 'asistencias:exportar_xlsx' %}">Exportar datos</a>
              <a href="{% url 'asistencias:exportar_xlsx' %}">Diplomaturas</a>
            {% endif %}
          {% else %}
            <a href="{% url 'account_login' %}">Ingresar</a>
            <a href="{% url 'account_signup' %}">Registrarse</a>
          {% endif %}
        </div>

        {% if request.user.is_authenticated %}
          <div class="nav-right">
            <a href="{% url 'account_logout' %}" class="btn-logout">Salir</a>
          </div>
        {% endif %}
      </nav>
    </div>
  </header>

  <main class="container">
    {% for message in messages %}
      <div class="alert">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
  </main>

  <footer class="footer">
    <div class="container">© 2025</div>
  </footer>
</body>
</html>